# --- Created by Slick DDL
# To stop Slick DDL generation, remove this comment and start using Evolutions

# --- !Ups

create table "Author" ("ID" BIGINT DEFAULT 9 GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL,"updatedat" TIMESTAMP NOT NULL,"updatedby" VARCHAR NOT NULL,"paperid" BIGINT NOT NULL,"personid" BIGINT NOT NULL,"position" INTEGER NOT NULL);
alter table "Author" add constraint "pk" primary key("ID","updatedat");
create table "Comment" ("ID" BIGINT DEFAULT 9 GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL,"updatedat" TIMESTAMP NOT NULL,"updatedby" VARCHAR NOT NULL,"paperid" BIGINT NOT NULL,"personid" BIGINT NOT NULL,"content" VARCHAR NOT NULL);
alter table "Comment" add constraint "pk" primary key("ID","updatedat");
create table "Email" ("ID" BIGINT DEFAULT 9 GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL,"updatedat" TIMESTAMP NOT NULL,"updatedby" VARCHAR NOT NULL,"to" VARCHAR NOT NULL,"subject" VARCHAR NOT NULL,"content" VARCHAR NOT NULL);
alter table "Email" add constraint "pk" primary key("ID","updatedat");
create table "File" ("ID" BIGINT DEFAULT 9 GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL,"updatedat" TIMESTAMP NOT NULL,"updatedby" VARCHAR NOT NULL,"name" VARCHAR NOT NULL,"size" BIGINT NOT NULL,"content" BLOB NOT NULL);
alter table "File" add constraint "pk" primary key("ID","updatedat");
create table "LOGIN_USERS" ("UID" TEXT NOT NULL,"PID" TEXT NOT NULL,"EMAIL" TEXT NOT NULL,"FIRSTNAME" TEXT NOT NULL,"LASTNAME" TEXT NOT NULL,"AUTHMETHOD" TEXT NOT NULL,"HASHER" TEXT,"PASSWORD" TEXT,"SALT" TEXT);
alter table "LOGIN_USERS" add constraint "LOGINUSERS_PK" primary key("UID","PID");
create table "Paper" ("ID" BIGINT DEFAULT 9 GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL,"updatedat" TIMESTAMP NOT NULL,"updatedby" VARCHAR NOT NULL,"title" VARCHAR NOT NULL,"format" INTEGER NOT NULL,"keywords" VARCHAR NOT NULL,"abstrct" VARCHAR NOT NULL,"nauthors" INTEGER NOT NULL,"file" BIGINT);
alter table "Paper" add constraint "pk" primary key("ID","updatedat");
create table "PaperTopic" ("ID" BIGINT DEFAULT 9 GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL,"updatedat" TIMESTAMP NOT NULL,"updatedby" VARCHAR NOT NULL,"paperid" BIGINT NOT NULL,"topicid" BIGINT NOT NULL);
alter table "PaperTopic" add constraint "pk" primary key("ID","updatedat");
create table "Person" ("ID" BIGINT DEFAULT 9 GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL,"updatedat" TIMESTAMP NOT NULL,"updatedby" VARCHAR NOT NULL,"firstname" VARCHAR NOT NULL,"lastname" VARCHAR NOT NULL,"organization" VARCHAR,"role" INTEGER NOT NULL,"email" VARCHAR NOT NULL);
alter table "Person" add constraint "pk" primary key("ID","updatedat");
create table "Review" ("ID" BIGINT DEFAULT 9 GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL,"updatedat" TIMESTAMP NOT NULL,"updatedby" VARCHAR NOT NULL,"paperid" BIGINT NOT NULL,"personid" BIGINT NOT NULL,"confidence" INTEGER NOT NULL,"evaluation" INTEGER NOT NULL,"content" VARCHAR NOT NULL);
alter table "Review" add constraint "pk" primary key("ID","updatedat");
create table "Topic" ("ID" BIGINT DEFAULT 9 GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL,"updatedat" TIMESTAMP NOT NULL,"updatedby" VARCHAR NOT NULL,"name" VARCHAR NOT NULL,"description" VARCHAR NOT NULL);
alter table "Topic" add constraint "pk" primary key("ID","updatedat");
create table "logintokens" ("uuid" text NOT NULL PRIMARY KEY,"email" text NOT NULL,"creationtime" TIMESTAMP NOT NULL,"expirationtime" TIMESTAMP NOT NULL,"issignup" BOOLEAN NOT NULL,"isinvitation" BOOLEAN NOT NULL);

# --- !Downs

alter table "Author" drop constraint "pk";
drop table "Author";
alter table "Comment" drop constraint "pk";
drop table "Comment";
alter table "Email" drop constraint "pk";
drop table "Email";
alter table "File" drop constraint "pk";
drop table "File";
alter table "LOGIN_USERS" drop constraint "LOGINUSERS_PK";
drop table "LOGIN_USERS";
alter table "Paper" drop constraint "pk";
drop table "Paper";
alter table "PaperTopic" drop constraint "pk";
drop table "PaperTopic";
alter table "Person" drop constraint "pk";
drop table "Person";
alter table "Review" drop constraint "pk";
drop table "Review";
alter table "Topic" drop constraint "pk";
drop table "Topic";
drop table "logintokens";

